all:	byteOrdering	server	client
	
byteOrdering:
	gcc -o byteOrdering byteOrdering.c

client:
	gcc -o client client.c

server:
	gcc -o server server.c

clean:
	rm -f byteOrdering
	rm -f client
	rm -f server
